// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _1473_VTKNgoc_Buoi3.Models;

#nullable disable

namespace _1473_VTKNgoc_Buoi3.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260605054216_ThemDuLieu")]
    partial class ThemDuLieu
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("_1473_VTKNgoc_Buoi3.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Thức ăn thú cưng"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Phụ kiện"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Chăm sóc sức khỏe"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Dịch vụ chăm sóc"
                        });
                });

            modelBuilder.Entity("_1473_VTKNgoc_Buoi3.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Hạt giàu protein, bổ sung vitamin giúp mèo khỏe mạnh và lông mượt.",
                            ImageUrl = "/images/Hat.jpg",
                            Name = "Hạt dinh dưỡng cho mèo",
                            Price = 185000m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Description = "Gối ngủ êm ái, giúp thú cưng nghỉ ngơi thoải mái trong mọi góc nhà.",
                            ImageUrl = "/images/GoiNgu.jpg",
                            Name = "Gối ngủ mềm cho thú cưng",
                            Price = 249000m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Description = "Không gian leo trèo và nghỉ ngơi gọn đẹp, phù hợp cho mèo năng động.",
                            ImageUrl = "/images/Cat.jpg",
                            Name = "Nhà cây cho mèo",
                            Price = 390000m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            Description = "Dịch vụ tắm, sấy và cắt tỉa lông giúp thú cưng sạch sẽ, thơm tho và thoải mái.",
                            ImageUrl = "/images/pet-banner.jpg",
                            Name = "Spa & Grooming cao cấp",
                            Price = 200000m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 4,
                            Description = "Không gian lưu trú sạch sẽ, có khu vui chơi và nhân viên theo dõi thú cưng trong ngày.",
                            ImageUrl = "/images/GoiNgu.jpg",
                            Name = "Khách sạn cho thú cưng",
                            Price = 350000m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 4,
                            Description = "Gói kiểm tra sức khỏe định kỳ và tư vấn tiêm phòng cần thiết cho chó mèo.",
                            ImageUrl = "/images/Cat.jpg",
                            Name = "Tiêm phòng & khám tổng quát",
                            Price = 150000m
                        });
                });

            modelBuilder.Entity("_1473_VTKNgoc_Buoi3.Models.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");
                });

            modelBuilder.Entity("_1473_VTKNgoc_Buoi3.Models.Product", b =>
                {
                    b.HasOne("_1473_VTKNgoc_Buoi3.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("_1473_VTKNgoc_Buoi3.Models.ProductImage", b =>
                {
                    b.HasOne("_1473_VTKNgoc_Buoi3.Models.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("_1473_VTKNgoc_Buoi3.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("_1473_VTKNgoc_Buoi3.Models.Product", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
