// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _1473_VTKNgoc_Buoi3.Models;

#nullable disable

namespace _1473_VTKNgoc_Buoi3.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260603132457_ThemDuLieu")]
    partial class ThemDuLieu
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("_1473_VTKNgoc_Buoi3.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Th?c an th� cung"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Ph? ki?n"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Cham s�c s?c kh?e"
                        });
                });

            modelBuilder.Entity("_1473_VTKNgoc_Buoi3.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "H?t gi�u protein, b? sung vitamin gi�p m�o kh?e m?nh v� l�ng mu?t.",
                            ImageUrl = "/images/Hat.jpg",
                            Name = "H?t dinh du?ng cho m�o",
                            Price = 185000m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Description = "G?i ng? �m �i, gi�p th� cung ngh? ngoi tho?i m�i trong m?i g�c nh�.",
                            ImageUrl = "/images/GoiNgu.jpg",
                            Name = "G?i ng? m?m cho th� cung",
                            Price = 249000m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Description = "Kh�ng gian leo tr�o v� ngh? ngoi g?n d?p, ph� h?p cho m�o nang d?ng.",
                            ImageUrl = "/images/Cat.jpg",
                            Name = "Nh� c�y cho m�o",
                            Price = 390000m
                        });
                });

            modelBuilder.Entity("_1473_VTKNgoc_Buoi3.Models.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");
                });

            modelBuilder.Entity("_1473_VTKNgoc_Buoi3.Models.Product", b =>
                {
                    b.HasOne("_1473_VTKNgoc_Buoi3.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("_1473_VTKNgoc_Buoi3.Models.ProductImage", b =>
                {
                    b.HasOne("_1473_VTKNgoc_Buoi3.Models.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("_1473_VTKNgoc_Buoi3.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("_1473_VTKNgoc_Buoi3.Models.Product", b =>
                {
                    b.Navigation("Images");
                });
#pragma warning restore 612, 618
        }
    }
}
